/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/aboutMe.vue')['default']
    Banner: typeof import('./src/components/banner.vue')['default']
    Contact: typeof import('./src/components/contact.vue')['default']
    FooterContent: typeof import('./src/components/footerContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TechCard: typeof import('./src/components/tech/techCard.vue')['default']
    TechStack: typeof import('./src/components/techStack.vue')['default']
  }
}
